version: "3.2"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - "REDIS_URL=redis://redis:6379/0"
      - "MONGODB_URL=mongodb://mongo:27017/0"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"