version: '3.2'

services:
  node:
    image: node:16
    volumes:
      - type: volume
        source: node_data
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  node_data: