version: '3.2'
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - type : volume
        source: db_data
        target: /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: monet
      POSTGRES_PASSWORD: monet
      POSTGRES_DB: monet
  tomcat:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      DRIVER_CLASS_NAME: org.postgresql.Driver
      LOGIN: monet
      PASSWORD: monet
      URL: jdbc:postgresql://3.125.151.179:5432/monet

volumes:
  db_data: